### ISSUE TITLE
AV detect

### ISSUE THREAD

**Issue by FalconG73** [cert-lv/exchange_webshell_detection#5]
Microsoft Defender detect this script Trojan:PowerShell/ExchangeWebshell.A!ibt....

**Comment by offlinehoster** [comment]
I can confirm this. Google Chrome as the downloading browser already abort this zip download because of virus detected.

**Comment by ghost** [comment]
I also Confirm, but i see inside the script $false_positives the hash values from the hack, i think that is why defender popped up.
Using MSERT.EXE /N from MS to find Infected files.

**Comment by FalconG73** [comment]
Is some solution to confirm false positive for this script ?

**Comment by ghost** [comment]
Windows Defender and others are reacting to keywords mentioned in the script (look at [line 94](https://github.com/cert-lv/exchange_webshell_detection/blob/c6fea9dae261cc4879931ad9c50546fcc0c0df66/detect_webshells.ps1#L94)). These strings are commonly seen in webshells - and looking for them is the whole point of this script, so we won't be changing it.

These strings are intentionally used unobfuscated, so that you can look inside and see for yourself what the script is doing. The intention of the script should be obvious - to go through certain folders and look for a number of strings which shouldn't be there. If you don't feel confident you understand what PowerShell is doing though, do not run it.

Hopefully your antivirus detecting this script is a sign that it is capable of detecting real webshells as well (which unfortunately wasn't the case during original attacks).

**Comment by FalconG73** [comment]
thanx
